approvals_reviewer = "user"
model = "gpt-5.5"
model_reasoning_effort = "medium"
suppress_unstable_features_warning = true
plan_mode_reasoning_effort = "xhigh"
service_tier = "default"
notify = ["/Users/divkix/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[notice]
fast_default_opt_out = true
hide_rate_limit_model_nudge = true

[notice.external_config_migration_prompts]
home_last_prompted_at = 1780595780

[plugins."github@openai-curated"]
enabled = true

[plugins."superpowers@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."code-simplifier@claude-plugins-official"]
enabled = true

[plugins."frontend-design@claude-plugins-official"]
enabled = true

[plugins."superpowers@claude-plugins-official"]
enabled = true

[plugins."typescript-lsp@claude-plugins-official"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[features]
terminal_resize_reflow = true
memories = true
external_migration = true
goals = true
mentions_v2 = true
js_repl = false

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-06-22T22:59:35Z"
source_type = "local"
source = "/Users/divkix/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.claude-plugins-official]
last_updated = "2026-06-22T22:59:38Z"
last_revision = "c7c2448b8153e7375980ce439d50d7228552e1ac"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-21T22:53:56Z"
source_type = "local"
source = "/Users/divkix/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/divkix/.codex"
CODEX_HOME = "/Users/divkix/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "2c20141b13bec5a64cd2874d8e2df011430d5b1a70e4f5425aa10d01743311a8"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.616.51431"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false
selected-avatar-id = "hoots"
